### ISSUE TITLE
Highfl

### ISSUE THREAD

**Issue by highfl** [codemaster123puppy/Blooket-Hacks-Working-Season-4-#1]
Hi! Is it okay if I put your spoof blooks on my github?

**Comment by highfl** [comment]
also what does add folder do

**Comment by codemaster123puppy** [comment]
Add folder lets you create a folder (i guess).
Also, you can take spoof blooks.

**Comment by codemaster123puppy** [comment]
SRY (sorry)  for the misunderstanding.

😳😳😳😳😳😳😳😳😳😳

**Comment by highfl** [comment]
its fine

**Comment by Consolehecker** [comment]
> its fine

just dont give him credit because he didn't make the hacks
