### ISSUE TITLE
how...

### ISSUE THREAD

**Issue by TampaFlorida** [codemaster123puppy/Blooket-Hacks-Working-Season-4-#2]
so im new and i really wanna beat my class at gold quest or blooket in general. so how do i actually use the hack

**Comment by blooketgamer243** [comment]
Are you on iPad or computer

**Comment by TampaFlorida** [comment]
> 

Im on computer (chromebook)

**Comment by codemaster123puppy** [comment]
Copy the code you want, Right-click, click inspect paste the code (cntrl+v), and close out of inspect.
